{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "071d1926_cc8aa27d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 31647
      },
      "writtenOn": "2020-12-22T01:26:10Z",
      "side": 1,
      "message": "Seems that the Trybots are still broken.",
      "revId": "273f9f00e584cf5ec10e86ddeaf8b271fa5e51de",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}