{
  "comments": [
    {
      "key": {
        "uuid": "7826f5b8_c876b0d4",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 7,
      "author": {
        "id": 5065
      },
      "writtenOn": "2019-01-31T15:55:32Z",
      "side": 1,
      "message": "what\u0027s inefficient about it? maybe \"unused\" or \"unread\" or \"unnecessary\"?",
      "range": {
        "startLine": 7,
        "startChar": 14,
        "endLine": 7,
        "endChar": 25
      },
      "revId": "d7d7d2cbbe02e9ccd6df016cb8c91b3d553bf59b",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "bf7dc5f4_d0941f1a",
        "filename": "src/bytes/buffer_test.go",
        "patchSetId": 1
      },
      "lineNbr": 170,
      "author": {
        "id": 5065
      },
      "writtenOn": "2019-01-31T15:55:32Z",
      "side": 1,
      "message": "All these test failure messages are pretty bad and not up to our (current) standards or style.\n\ne.g. line 163: what was the error? and how do you know it\u0027s EOF?\n\nline 166: what was expected? and quote them both.\n\nline 170: \"unexpected not eof\"? No, it was unexpected success reading a byte. So which byte? I\u0027d keep the assignment to c but show it in the error message.",
      "range": {
        "startLine": 162,
        "startChar": 17,
        "endLine": 170,
        "endChar": 41
      },
      "revId": "d7d7d2cbbe02e9ccd6df016cb8c91b3d553bf59b",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705",
      "unresolved": true
    }
  ]
}