{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "3f1a1b8a_32e80114",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 51444
      },
      "writtenOn": "2023-08-31T22:45:59Z",
      "side": 1,
      "message": "The windows-amd64-2016 failure looks unrelated to me, TestDialTimeout in package net is unhappy and I don\u0027t think I got anywhere near it.\n\nThe other trybot failure was real, I didn\u0027t know about documenting the exposed API change in api/next. That\u0027s now fixed.",
      "revId": "db0868c771b224e8fd573c3a8470c7e177596672",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}