{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f8259040_a737b810",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 34895
      },
      "writtenOn": "2024-09-05T00:38:17Z",
      "side": 1,
      "message": "Thanks.",
      "revId": "e541514b9cba5246d62aee7ca3eb12ae9f025aec",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6abb4fc9_fd401a84",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 34895
      },
      "writtenOn": "2024-09-05T00:42:17Z",
      "side": 1,
      "message": "Trybot failures may be real.",
      "revId": "e541514b9cba5246d62aee7ca3eb12ae9f025aec",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}